login: &login
  adapter: postgresql
  username: postgres
  password: 
  host: localhost

development:
  <<: *login
  database: zelena_kuchyne_dev

test:
  <<: *login
  database: zelena_kuchyne_test

production:
  <<: *login
  database: zelena_kuchyne
 
