CREATE TABLE user_import (
  iduziv integer NOT NULL,
  loginname varchar(50) NOT NULL,
  passwdmd5 varchar(150) NOT NULL,
  passwduziv varchar(150) NOT NULL,
  jmeno varchar(100) NOT NULL,
  prijmeni varchar(100) NOT NULL,
  email varchar(200) NOT NULL,
  telefon varchar(12) NOT NULL,
  adresa varchar(200) NOT NULL,
  mesto varchar(100) NOT NULL,
  psc varchar(7) NOT NULL,
  dodani integer NOT NULL,
  jmenodod varchar(100) NOT NULL,
  prijmenidod varchar(100) NOT NULL,
  adresadod varchar(200) NOT NULL,
  mestodod varchar(100) NOT NULL,
  pscdod varchar(7) NOT NULL,
  firma varchar(255) NOT NULL,
  ico varchar(25) NOT NULL,
  dic varchar(25) NOT NULL,
  objednavek integer NOT NULL,
  cena_objednavek integer NOT NULL,
  sleva integer  NOT NULL,
  last_order timestamp,
  skip boolean NOT NULL default false,
  updated boolean NOT NULL DEFAULT false,
  user_id integer REFERENCES users(id)
);